# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' matrix2df
#' @name matrix2df
#' @description conversion from matrix to DataFrame
#' @param x matrix
NULL

matrix2df <- function(x) {
    .Call(`_chunkR_matrix2df`, x)
}

#' chunker, matrix-constructor
#' @keywords internal
NULL

#' chunker, dataframe-constructor
#' @keywords internal
NULL

#' chunker__destructor 
#' @keywords internal
NULL

#' chunker__next_chunk
#' @keywords internal
NULL

#' chunker__next_chunk_matrix
#' @keywords internal
NULL

#' chunker__next_chunk_df
#' @keywords internal
NULL

#' chunker__set_colnames 
#' @keywords internal
NULL

#' set_generic_rownames
#' @keywords internal
NULL

#' set_generic_colnames
#' @keywords internal
NULL

#'get_matrix
#'@keywords internal
NULL

#'get_dataframe
#'@keywords internal
#'
NULL

#' chunker__get_colnames
#' @keywords internal
NULL

#' chunker__get_completed
#' @keywords internal
NULL

#' chunker__get_type
#' @keywords internal
NULL

#' mixed_list
#' @keywords internal
NULL

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_chunkR_RcppExport_registerCCallable', PACKAGE = 'chunkR')
})
