# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param x A single integer.
#' @export
reader__new <- function(path_, sep_, header_, has_row_names_, chunksize_) {
    .Call(`_reader_reader__new`, path_, sep_, header_, has_row_names_, chunksize_)
}

#' @param x A single integer.
#' @export
reader__set_header <- function(ptr) {
    .Call(`_reader_reader__set_header`, ptr)
}

#' @param x A single integer.
#' @export
reader__next_chunk <- function(ptr) {
    .Call(`_reader_reader__next_chunk`, ptr)
}

#' @param x A single integer.
#' @export
reader__get_header <- function(ptr) {
    .Call(`_reader_reader__get_header`, ptr)
}

#' @param x A single integer.
#' @export
reader__get_data <- function(ptr) {
    .Call(`_reader_reader__get_data`, ptr)
}

#' @param x A single integer.
#' @export
reader__get_completed <- function(ptr) {
    .Call(`_reader_reader__get_completed`, ptr)
}

#' reader
#' @description reader object constructor
#' @param path Input file path 
#' @param sep Character separating cells 
#' @param header Header present (Logical)
#' @param has_rown_names Row names present (Logical)
#' @param chunksize Size of chunk (Logical)
NULL

#' destructor 
#' @description header destructor
NULL

#' set_header 
#' @description set file header
NULL

#' next_chunk
#' @description read next chunk
NULL

#' get_header
#' @description get table header
NULL

#' get_data
#' @description get data chunk stored in object
NULL

#' get_completed
#' @description get the number of lines read
NULL

#' reader_module
#' @description reader module
NULL

